name: Comment on Pull Request!
branding:
  icon: 'message-square'
  color: 'olive'

inputs:
  gh_token:
    required: true
    default: ${{ github.token }}
  
  comment_body:
    type: string
    required: true

runs:
  using: composite  
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.gh_token }}
        fetch-depth: 0

    - name: Comment on PR
      shell: bash
      run: |
        gh pr comment ${{ github.event.number }} --body "${{ inputs.comment_body }}"
      env:
        GH_TOKEN: ${{ inputs.gh_token }}