inputs:
  gh_token:
    type: string
    requiered: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.gh_token }}
        fetch-depth: 0

    - name: Check ChangeLog
      run: |
        if ! echo "${{ github.event.pull_request.title }}" | grep -q "\[DEV\]"; then
          PR_CHANGED_FILES=$(git --no-pager diff --name-only "origin/${{ github.base_ref }}...origin/${{ github.head_ref }}")
          if echo "$PR_CHANGED_FILES" | grep -q "CHANGELOG.md"; then
            exit 0
          else
            echo "No changes found in CHANGELOG.md."
            exit 1
          fi
        else
          exit 0
        fi
      shell: bash

