inputs:
  gh_token:
    type: string
    requiered: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.gh_token }}
        fetch-depth: 0

    - name: Check ChangeLog
      id: check_changelog
      run: |
        if echo "${{ github.event.pull_request.title }}" | grep -q "\[DEV\]"; then
          exit 0
        fi

        PR_CHANGED_FILES=$(git --no-pager diff --name-only "origin/${{ github.base_ref }}...origin/${{ github.head_ref }}")
        if ! echo "$PR_CHANGED_FILES" | grep -q "CHANGELOG.md"; then
          echo "::warning title=CHANGELOG Update Required::No changes found in CHANGELOG.md..."
          echo "changelog_missing=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - uses: mayo-tds/workflows_demo/comment_pullrequest@master  
      if: steps.check_changelog.outputs.changelog_missing == 'true'
      with:
        gh_token: ${{ inputs.gh_token }}
        comment_body: |
          ### ⚠️ CHANGELOG Update Required ⚠️


          No changes found in `CHANGELOG.md`. Please either:

          - [ ] Add your changes to the CHANGELOG
          - [ ] Add `[DEV]` prefix to your PR title or commit messages if no CHANGELOG entry is needed

          > See our [Changelog Guidelines](https://tripledotstudios.atlassian.net/wiki/spaces/RCTR/pages/3735126037/Changelog+Guidelines) for more information.
