inputs:
  gh_token:
    type: string
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.gh_token }}
        fetch-depth: 0

    - name: Check for Existing Comment
      id: check_comment
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      shell: bash
      run: |
        # Fetch existing comments on the PR
        COMMENTS=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
          "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments")

        # Check if the specific message already exists
        if echo "$COMMENTS" | grep -q "⚠️ CHANGELOG Update Required ⚠️"; then
          echo "Comment already exists. Exiting early."
          echo "comment_exists=true" >> $GITHUB_OUTPUT
        fi

    - name: Check ChangeLog
      id: check_changelog
      if: steps.check_comment.outputs.comment_exists != 'true'
      shell: bash
      run: |
        # '[DEV]' is present on pull request title => No changelog update required
        if echo "${{ github.event.pull_request.title }}" | grep -q "\[DEV\]"; then
          exit 0
        fi

        # CHANGELOG.md is present on updated files => All's right with the world...
        PR_CHANGED_FILES=$(git --no-pager diff --name-only "origin/${{ github.base_ref }}...origin/${{ github.head_ref }}")
        if echo "$PR_CHANGED_FILES" | grep -q "CHANGELOG.md"; then
            exit 0
        fi

        # if we are here, means that a CHANGELOG update is missing...
        # Set a warning and assign 'changelog_missing' variable to 'true'
        echo "::warning title=CHANGELOG Update Required::No changes found in CHANGELOG.md..."
        echo "changelog_missing=true" >> $GITHUB_OUTPUT

    #- uses: tripledotstudios/platform-actions/comment_on_pull_request@main
    - uses: mayo-tds/workflows_demo/comment_pullrequest@master  
      if: steps.check_changelog.outputs.changelog_missing == 'true'
      with:
        gh_token: ${{ inputs.gh_token }}
        comment_body: |
          ### ⚠️ CHANGELOG Update Required ⚠️


          No changes found in \`CHANGELOG.md\`. Please either:

          - [ ] Add your changes to the CHANGELOG
          - [ ] Add `[DEV]` prefix to your PR title or commit messages if no CHANGELOG entry is needed

          > See our [Changelog Guidelines](https://tripledotstudios.atlassian.net/wiki/spaces/RCTR/pages/3735126037/Changelog+Guidelines) for more information.
