name: Check ChangeLog

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
          
jobs:
  check_changelog:
    name: "Check ChangeLog"
    runs-on: [ubuntu-latest]

    steps:
      - uses: workflows_demo/platform-actions/check_changelog@main
        with:
          gh_token: ${{ secrets.TDS_MAYO_GITHUB_TOKEN }}
