name: Check ChangeLog
run-name: Check ChangeLog on ${{ github.event.workflow_run.head_commit.message }}!

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
          
jobs:
  check_changelog:
    name: "Check ChangeLog"
    runs-on: [ubuntu-latest]

    steps:
      - uses: mayo-tds/workflows_demo/check_changelog@master
        with:
          gh_token: ${{ secrets.TDS_MAYO_GITHUB_TOKEN }}
