name: Check ChangeLog

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
          
jobs:
  check_changelog:
    name: "Check ChangeLog"
    runs-on: [self-hosted, lightweight ]

    steps:
      # - uses: tripledotstudios/platform-actions/check_changelog@main
      - uses: myo-tds/workflows_demo/check_changelog@main
        id: check_changelog_step
        with:
          gh_token: ${{ secrets.TDS_AUTOBOT_GITHUB_TOKEN }}

      
      # - uses: tripledotstudios/platform-actions/comment_on_pull_request@master
      - uses: mayo-tds/workflows_demo/comment_on_pull_request@master
        with:
          gh_token: ${{ secrets.TDS_AUTOBOT_GITHUB_TOKEN }}
          comment_body: |
            ### ⚠️ CHANGELOG Update Required ⚠️


            No changes found in `CHANGELOG.md`. Please either:

            - [ ] Add your changes to the CHANGELOG
            - [ ] Add `[DEV]` prefix to your PR title or commit messages if no CHANGELOG entry is needed

            > See our [Changelog Guidelines](https://tripledotstudios.atlassian.net/wiki/spaces/RCTR/pages/3735126037/Changelog+Guidelines) for more information.
