name: Comment as Action

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
          
jobs:
  comment:
    name: "Add comment!"
    runs-on: [ubuntu-latest]
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: mayo-tds/workflows_demo/pr_comment@master
        with:
          gh_token: ${{ secrets.TDS_MAYO_GITHUB_TOKEN }}
          MSG_BODY: "Wel well well,, what do we have here!?"
